# Generated by Django 3.1.3 on 2020-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=250)),
                ('id_user', models.IntegerField()),
            ],
            options={
                'db_table': 'Nodes',
            },
        ),
    ]
